# Конфигурация golangci-lint для GoKB Embedder

run:
  timeout: 5m
  go: "1.21"
  modules-download-mode: readonly

linters-settings:
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 15
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 3
  misspell:
    locale: US
  lll:
    line-length: 140
  goimports:
    local-prefixes: gokb-embedder
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - exhaustive
    - forbidigo
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomnd
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - makezero
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - promlinter
    - revive
    - rowserrcheck
    - staticcheck
    - structcheck
    - stylecheck
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
    - wrapcheck

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - goconst
        - funlen
        - gocyclo
        - dupl
        - gocritic
        - thelper
        - tparallel
    - path: internal/utils/tokenizer_test\.go
      linters:
        - gomnd
    - path: examples/
      linters:
        - gomnd
        - goconst
        - funlen
        - gocyclo
        - dupl
        - gocritic
        - thelper
        - tparallel
        - gosec
        - govet
        - staticcheck
        - stylecheck
        - unused
        - varcheck
        - whitespace
        - wrapcheck
        - errcheck
        - ineffassign
        - nakedret
        - noctx
        - prealloc
        - predeclared
        - promlinter
        - revive
        - rowserrcheck
        - structcheck
        - unconvert
        - unparam
        - bodyclose
        - deadcode
        - depguard
        - dogsled
        - dupl
        - exportloopref
        - exhaustive
        - forbidigo
        - gochecknoinits
        - goconst
        - gocyclo
        - gofmt
        - gofumpt
        - goheader
        - goimports
        - gomnd
        - gomodguard
        - goprintffuncname
        - gosec
        - gosimple
        - govet
        - ineffassign
        - lll
        - makezero
        - misspell
        - nakedret
        - noctx
        - nolintlint
        - prealloc
        - predeclared
        - promlinter
        - revive
        - rowserrcheck
        - staticcheck
        - structcheck
        - stylecheck
        - thelper
        - tparallel
        - typecheck
        - unconvert
        - unparam
        - unused
        - varcheck
        - whitespace
        - wrapcheck
  max-issues-per-linter: 0
  max-same-issues: 0 