# Автоматическое создание релизов при тегировании
name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    name: Создание релиза
    runs-on: ubuntu-latest
    steps:
    - name: Checkout кода
      uses: actions/checkout@v4

    - name: Настройка Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        cache: true

    - name: Установка зависимостей
      run: make deps

    - name: Создание релиза
      run: make release

    - name: Создание GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          release/*.tar.gz
          release/*.zip
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 